### PR TITLE
Responsive Functional

### PR DESCRIPTION
**Pull request by kaeky**
+ shorten the url of the blockchain that will come from the api
+ change boostrap to https://mdbootstrap.com/, it is more aesthetic
+ the page is responsive for most phones

### CODE REVIEW

**Comment by cryptorex** [comment]
woops got conflicts now cause I merged the other PR - can you resolve please @kaeky

**Comment by kaeky** [comment]
> woops got conflicts now cause I merged the other PR - can you resolve please @kaeky

OK

**Comment by kaeky** [comment]
it is already solved

**Comment by cryptorex** [comment]
@MarcelusCH when you have a chance can you please try to test this PR in your environment - I've already merged the previous PR to master.

**Comment by Sufod** [comment]
I tested it on my env, seems good !

Screenshot from 2021-05-22 11-54-49
Screenshot from 2021-05-22 11-54-39
Screenshot from 2021-05-22 11-54-22
Screenshot from 2021-05-22 11-54-06

**Comment by cryptorex** [comment]
@Sufod excellent!  Thanks for testing. I'll merge.

@MarcelusCH I think you're hosting this - please merge master into your production environment when you have a chance.

thanks everyone!

**Pull request merged**
